# Default rendering parameters of BlenderRenderer. Each one may be overridden with a System property
# prefixed by the class name, for example -Dsh3d.gpurenderer.BlenderRenderer.highQuality.samples=1024

# Maximum count of samples per pixel computed by Cycles before denoising
lowQuality.samples=64
highQuality.samples=256
